package com.imjustdoom.minecrash.database;

import com.imjustdoom.minecrash.Main;
import lombok.Getter;

import java.sql.*;

@Getter
public class DatabaseConnection {

    public Statement stmt;
    public Connection conn;

    public DatabaseConnection() {
        String user = Main.config.user;
        String pass = Main.config.password;
        String server = Main.config.host;
        String port = Main.config.port;
        String database = Main.config.database;

        //Connect and setup database
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                    "jdbc:mysql://" + server + ":" + port + "/" + database, user, pass);
            stmt = conn.createStatement();

            createSQLTables();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public PreparedStatement prepareStatement(String sql) {
        try {
            return conn.prepareStatement(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        try {
            return conn.prepareStatement(sql, autoGeneratedKeys);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    private void createSQLTables() throws SQLException {
        String sql = "CREATE TABLE IF NOT EXISTS review (" +
                "`id` INT NOT NULL AUTO_INCREMENT, " +
                "`userId` VARCHAR(20) NOT NULL, " +
                "`error` VARCHAR(3600) NOT NULL, " +
                "PRIMARY KEY (`id`) " +
                ") ENGINE=InnoDB;";

        stmt.executeUpdate(sql);
    }

    public String addErrorForReview(String userId, String error) {
        String sql = "INSERT INTO review (userId, error) VALUES (?, ?)";
        try {
            PreparedStatement preparedStatement = prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            preparedStatement.setString(1, userId);
            preparedStatement.setString(2, error);
            preparedStatement.executeUpdate();

            ResultSet rs = preparedStatement.getGeneratedKeys();
            if(rs.next()) {
                return rs.getString(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return "-1";
    }

    public void removeErrorForReview(String id) {
        String sql = "DELETE FROM review WHERE id = ?";
        try {
            PreparedStatement preparedStatement = prepareStatement(sql);
            preparedStatement.setString(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public boolean containsErrorForReview(String id) {
        String sql = "SELECT id FROM review WHERE id = ?";
        try {
            PreparedStatement preparedStatement = prepareStatement(sql);
            preparedStatement.setString(1, id);
            ResultSet rs = preparedStatement.executeQuery();
            return rs.next();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    public String getErrorFromReview(int id) {
        String sql = "SELECT error FROM review WHERE id = ?";
        try {
            PreparedStatement preparedStatement = prepareStatement(sql);
            preparedStatement.setInt(1, id);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()) {
                return rs.getString(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return null;
    }

    public String getUserIdFromReview(int id) {
        String sql = "SELECT userId FROM review WHERE id = ?";
        try {
            PreparedStatement preparedStatement = prepareStatement(sql);
            preparedStatement.setInt(1, id);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()) {
                return rs.getString(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return null;
    }
}
